---
- name: Ensure Satellite systems are configured
  hosts: "{{ hostlist | default('all') }}"

  tasks:

    - name: Configure various components on the Satellite server
      block:

        - name: Print Satellite installation parameters
          ansible.builtin.debug:
            msg: "{{ inventory_hostname }}, {{ satellite_username }}, {{ satellite_password }}, {{ satellite_organization }}, {{ satellite_location }} {{ satellite_manifest_path }}"
            verbosity: 1

        - name: Ensure the Satellite server name is defined
          ansible.builtin.set_fact:
            satellite_server_url: "https://{{ ansible_host }}"

        - name: Print Satellite server connection information
          ansible.builtin.debug:
            msg: "Configuring Satellite server at {{ satellite_server_url }}"

        - name: Ensure manifest is installed
          ansible.builtin.include_role:
            name: redhat.satellite.manifest

        - name: Ensure products are selected
          ansible.builtin.include_role:
            name: redhat.satellite.repositories

        - name: Synchronize repositories (leave out repository specification to sync all repositories)
          redhat.satellite.repository_sync:
            username: "{{ satellite_username }}"
            password: "{{ satellite_password}}"
            server_url: "{{ satellite_server_url }}"
            product: "{{ item.name }}"
            organization: "{{ satellite_organization }}"
            validate_certs: no
          with_items: "{{ satellite_products }}"
#          async: 7200
#          poll: 60

        - name: Ensure Lifecycles are created
          ansible.builtin.include_role:
            name: redhat.satellite.lifecycle_environments

        - name: Ensure Content Views are created
          ansible.builtin.include_role:
            name: redhat.satellite.content_views

        - name: Loop over all the content views/filter definitions and ensure they are created and published
          ansible.builtin.include_tasks:
            file: files/content_view_loop_tasks.yml
          loop: "{{ satellite_content_views_to_publish }}"

        - name: Ensure Activation Keys are created
          ansible.builtin.include_role:
            name: redhat.satellite.activation_keys

      delegate_to: localhost
