---
- name: Update a Content View with all errata up to a specified date and publish to a set of environments
  gather_facts: false
  hosts: "{{ hostlist | default('all') }}"
  vars:
    satellite_exclude_start_date: ""
    satellite_content_view: ""
    satellite_target_lifecycle_environments:
      - Library
      - Dev
      - Test

  tasks:

    - name: Run this on localhost but pickup the host_vars associated with the specified inventory_hostname
      block:

        - name: Verify that satellite_exclude_start_date and satellite_content_view are defined
          ansible.builtin.assert:
            fail_msg: "satellite_exclude_start_date and satellite_content_view must be defined"
            that:
              - satellite_exclude_start_date is defined and satellite_exclude_start_date|length > 0
              - satellite_content_view is defined and satellite_content_view|length > 0

        - name: Ensure the Satellite server name is defined
          set_fact:
            satellite_server_url: "https://{{ ansible_host }}"

        - name: Print Satellite server connection information
          debug:
            msg: "Configuring Satellite server at {{ satellite_server_url }}"

        - name: Print the filter date
          debug:
            msg: "Specified date is {{ satellite_exclude_start_date }}"

        - name: Define variable
          set_fact:
            satellite_content_views_to_publish:
              - organization: "{{ satellite_organization }}"
                password: "{{ satellite_password }}"
                server_url: "{{ satellite_server_url }}"
                username: "{{ satellite_username }}"
                validate_certs: "{{ satellite_validate_certs }}"
                content_view: "{{ satellite_content_view }}"
                description: "All packages, errata excluded starting {{ satellite_exclude_start_date }}"
                force_promote: True
                lifecycle_environments: "{{ satellite_target_lifecycle_environments }}"
                state: present
#                version: "{{ satellite_exclude_start_date }}"
#                version: "4.0"
                content_view_filters:
                  - date_type: updated
                    description: Exclude errata after a given date
                    filter_state: present
                    filter_type: erratum
                    inclusion: no
                    name: Errata-To-Date
                    rule_state: present
                    start_date: "{{ satellite_exclude_start_date }}"
                    types:
                      - bugfix
                      - enhancement
                      - security
          when: satellite_exclude_start_date is defined and satellite_exclude_start_date|length > 0

        - name: Print Content View information
          debug:
            var: item
          loop: "{{ satellite_content_views_to_publish }}"
          when: satellite_content_views_to_publish is defined

        - name: Loop over all the content views/filter definitions and ensure they are created and published
          include_tasks:
            file: files/content_view_loop_tasks.yml
          loop: "{{ satellite_content_views_to_publish }}"
          when: satellite_content_views_to_publish is defined

      delegate_to: localhost
